# Generated by Django 5.2.4 on 2025-07-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='breand',
            new_name='brend',
        ),
    ]
